---
  wp1_preprocess_transfer_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "stanley"
  wp1_preprocess_transfer_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"
  wp1_preprocess_transfer_ip:
    description: The host where pre-process data should be pushed to.
    type: string
    required: true
    default: "130.238.54.142"
  wp1_preprocess_transfer_prefix_location:
    description: Location on transfer host where data will be stored.
    type: string
    required: true
    default: "/projects/wp1/nobackup"
  wp1_preprocess_storage_path:
    description: Location on transfer host where data will be stored.
    type: string
    required: true
    default: "/data/wp1"

  wp1_process_local_prefix_location:
    description: Local folder-prefix used during processing.
    type: string
    required: true
    default: "/data/wp1/nobackup"
  wp1_processing_host_ip:
    description: The host where pre-process data should be pushed to.
    type: string
    required: true
    default: "130.238.54.142"
  wp1_processing_host_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "stanley"
  wp1_processing_host_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"

  wp1_transfer_from_host_ip:
    description: The host where outbox data will be retrieved.
    type: string
    required: true
    default: "130.238.54.142"
  wp1_tansfer_from_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "stanley"
  wp1_tansfer_from_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"
  wp1_transfer_from_runfolder_port:
    description: The port used to communiction with remote runfolder service.
    type: string
    required: true
    default: "10801"
  wp1_fetch_to_prefix:
    description: Local folder-prefix used to store the retrieved data.
    type: string
    required: true
    default: "/data/wp1"


  wp1_runfolder_api_version:
    description: The arteria-runfolder api version that should be used.
    type: string
    required: true
    default: "1.0"
  wp1_notification_mail_lab:
    description: Email address where notifications to lab will be sent.
    type: string
    required: true
    default: "lab@googlegroups.com"
  wp1_notification_mail_bioinfo:
    description: Email address where notifications to bioinformatic will be sent.
    type: string
    required: true
    default: "bio@googlegroups.com"
  wp1_runfolder_service_port:
    description: Port that will be used to send requests to the runfolder service, for wp1
    type: string
    required: true
    default: "10800"
  wp1_runfolder_service_address:
    description: Address that will be used to send requests to the runfolder service, for wp1
    type: string
    required: true
    default: "wp1runfolder"
  wp1_sera_version:
    description: Sera version that will be loaded.
    type: string
    required: true
    default: "18.0.2"
  wp1_slurm_version:
    description: Slurm version that will be loaded.
    type: string
    required: true
    default: "16.05.11"
  wp1_ref_files_location:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "/data/ref_data/wp1"

  wp2_notification_mail_lab:
    description: Email address where notifications to lab will be sent.
    type: string
    required: true
    default: "lab@googlegroups.com"
  wp2_notification_mail_bioinfo:
    description: Email address where notifications to bioinformatic will be sent.
    type: string
    required: true
    default: "bio@googlegroups.com"
  wp2_runfolder_api_version:
    description: The arteria-runfolder api version that should be used.
    type: string
    required: true
    default: "1.0"

  wp2_runfolder_service_address:
      description: Address that will be used to send requests to the runfolder service, for wp1
      type: string
      required: true
      default: "wp1runfolder"
  wp2_runfolder_service_port:
    description: Port that will be used to send requests to the runfolder service, for wp1
    type: string
    required: true
    default: "10800"
  wp2_preprocess_transfer_ip:
    description: The host where pre-process data should be pushed to.
    type: string
    required: true
    default: "130.238.54.142"
  wp2_preprocess_transfer_prefix_location:
    description: Location on transfer host where data will be stored.
    type: string
    required: true
    default: "/projects/wp2/nobackup"
  wp2_preprocess_transfer_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"
  wp2_preprocess_transfer_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "stanley"

  wp2_process_local_prefix_location:
    description: Local folder-prefix used during processing.
    type: string
    required: true
    default: "/data/wp2/nobackup"
  wp2_processing_host_ip:
    description: The host where pre-process data should be pushed to.
    type: string
    required: true
    default: "130.238.54.142"
  wp2_processing_host_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"
  wp2_processing_host_user:
      description: The user that will be used to push data.
      type: string
      required: true
      default: "stanley"
  wp2_slurm_version:
    description: Slurm version that will be loaded.
    type: string
    required: true
    default: "16.05.11"
  wp2_slurm_version:
    description: Slurm version that will be loaded.
    type: string
    required: true
    default: "16.05.11"

  wp2_transfer_from_host_ip:
    description: The host where outbox data will be retrieved.
    type: string
    required: true
    default: "130.238.54.142"
  wp2_transfer_from_runfolder_port:
    description: The port used to communiction with remote runfolder service.
    type: string
    required: true
    default: "10801"
  wp2_tansfer_from_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "stanley"
  wp2_tansfer_from_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "~/.ssh/id_rsa"
  wp2_preprocess_storage_path:
    description: Location on transfer host where data will be stored.
    type: string
    required: true
    default: "/data/wp2"
  wp2_fetch_to_prefix:
    description: Local folder-prefix used to store the retrieved data.
    type: string
    required: true
    default: "/data/wp2"


  wp3_processing_host_ip:
      description: The host where pre-process data should be pushed to.
      type: string
      required: true
      default: "130.238.54.142"
  wp3_processing_host_user:
      description: The user that will be used to push data.
      type: string
      required: true
      default: "patsm159"
  wp3_processing_host_key:
      description: The key that will be used transfer data.
      type: string
      required: true
      default: "/home/stanley/.ssh/moriarty_rsa"
  wp3_notification_mail_lab:
      description: Email address where notifications to lab will be sent.
      type: string
      required: true
      default: "andrei.alexsson@scilifelab.uu.se"
  wp3_runfolder_service_port:
      description: Port that will be used to send requests to the runfolder service, for wp1
      type: string
      required: true
      default: "10800"
  wp3_transfer_from_host_port:
      description: The port used to communiction with remote runfolder service.
      type: string
      required: true
      default: "10801"
  wp3_transfer_from_host_ip:
      description: The host where outbox data will be retrieved.
      type: string
      required: true
      default: "130.238.54.142"
  wp3_transfer_from_user:
      description: The user that will be used to push data.
      type: string
      required: true
      default: "patsm159"
  wp3_transfer_from_key:
      description: The key that will be used transfer data.
      type: string
      required: true
      default: "/home/stanley/.ssh/moriarty_rsa"
  wp3_preprocess_transfer_user:
    description: The user that will be used to push data.
    type: string
    required: true
    default: "patsm159"
  wp3_preprocess_transfer_key:
    description: The key that will be used transfer data.
    type: string
    required: true
    default: "/home/stanley/.ssh/moriarty_rsa"
  wp3_preprocess_transfer_ip:
    description: The host where pre-process data should be pushed to.
    type: string
    required: true
    default: "130.238.54.142"
  wp3_preprocess_transfer_prefix_location:
    description: Location on transfer host where data will be stored.
    type: string
    required: true
    default: "/projects/wp3/nobackup/"
  wp3_runfolder_api_version:
    description: The arteria-runfolder api version that should be used.
    type: string
    required: true
    default: "1.0"