---
name: "wp1_preprocssing_inbox"
pack: "auctornotitia"
description: "..."
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/INBOX/"

action:
    ref: "auctornotitia.pre_process_wp1_data"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"