---
name: "wp1_devel_fetch_outbox"
pack: "ductus"
description: "Rule that triggers a fetching action, when a development wp1 experiment has been submitted to the outbox."
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/ngs/utveckling/OUTBOX"

action:
    ref: "ductus.wp1_fetch_outbox"
    parameters:
        runfolder_host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
        project_type: utveckling