---
name: "auctornotitia.wp1_inbox_data"
description: "..."
enabled: true

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "regex"
      pattern: "^.+/OUTBOX/.+$"

action:
    ref: "auctornotitia.process_wp1_inbox_data"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"