---
name: "wp1_devel_process_inbox"
pack: "ductus"
description: "Rule that triggers a processing action, when a development wp1 experiment has been submitted to the inbox"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/ngs/utveckling/INBOX/"

action:
    ref: "ductus.wp1_process_inbox"
    parameters:
        runfolder: "{{trigger.runfolder}}"
        runfolder_host: "{{trigger.host}}"
        project_type: "utveckling"