---
name: "process_wp1_inbox_data"
pack: "ductus"
description: "..."
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "/wp1/INBOX/"

action:
    ref: "ductus.process_wp1_inbox_data"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"