---
name: "wp2_processing_inbox"
pack: "auctornotitia"
description: "..."
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
      type: "contains"
      pattern: "wp2/INBOX"

action:
    ref: "auctornotitia.process_wp2_inbox_data"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"