---
name: "wp3_preprocessing_inbox"
pack: "ductus"
description: "Transfer files to cluster"
enabled: false

trigger:
  type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
        type: "contains"
        pattern: "/AL_NGS-Workarea/KG_Workarea/NextSeq1_Runfolder/"

action:
    ref: "ductus.wp3_preprocessing_inbox"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"
