---
name: "wp3_processing_inbox_CCP17"
pack: "ductus"
description: "CCP17 rule running on facility cluster"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
        type: "contains"
        pattern: "/projects/wp3/nobackup/CCP17/INBOX/"

action:
    ref: "ductus.wp3_process_inbox"
    parameters:
        host: "{{trigger.host}}"
        SS_folder: "{{trigger.runfolder}}"
        runpanel: "CCP17"