---
name: "wp3_outbox_data_CREV2"
pack: "ductus"
description: "Check if new data needs to be transfered"
enabled: false

trigger:
    type: "arteria.runfolder_ready"

criteria:
    trigger.runfolder:
        type: "contains"
        pattern: "/projects/wp3/nobackup/CREV2/OUTBOX/"

action:
    ref: "ductus.wp3_retrieve_result"
    parameters:
        host: "{{trigger.host}}"
        TE_folder: "{{trigger.runfolder}}"
        runpanel: "CREV2"
